### ISSUE TITLE
pdm-multirun not work with PDM 2.7.4

### ISSUE THREAD

**Issue by natir** [pawamoy/pdm-multirun#2]
**Describe the bug**
Y update my version of pdm to 2.7.4

**To Reproduce**
1. Go to any pdm project
2. Run command `pdm self update`
3. Check pdm version `pdm --version` == 2.7.4
4. Run command `pdm multirun run`

**Expected behavior**
Not bug

**Screenshots**
Result of reproduce:
```
[AttributeError]: module 'pdm.cli.actions' has no attribute 'do_use'
Add '-v' to see the detailed traceback
```

**System (please complete the following information):**
- pdm version: 2.7.4
- python version: 3.11
- OS: Linux
